"""
Read metrics.json (produced by regenerate_figures.py) and emit metrics.tex
defining every \\REG... and \\CLF... and \\DC... and \\DS... macro used in main.tex.

This guarantees that every numerical claim in the report comes from a real
execution of the pipeline.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
metrics = json.loads((HERE / "metrics.json").read_text())

reg = metrics["regression"]
clf = metrics["classification"]
dc  = metrics["class_distribution"]
n_rows     = metrics["n_rows"]
n_features = metrics["n_features"]


def fmt3(v):  return f"{v:.3f}"
def fmt4(v):  return f"{v:.4f}"
def pct(v, d=1): return f"{v*100:.{d}f}\\%"

# best-model selection
best_reg_key = max(reg, key=lambda k: reg[k]["R2"])
best_clf_key = max(clf, key=lambda k: clf[k]["F1"])

# total class share for percentages
total = dc["short"] + dc["medium"] + dc["long"]
short_pct  = pct(dc["short"]  / total)
medium_pct = pct(dc["medium"] / total)
long_pct   = pct(dc["long"]   / total)

# Map model display name (key in metrics.json) to LaTeX macro stem
REG_MAP = {
    "Linear Regression":      "LR",
    "Decision Tree":          "DT",
    "Random Forest (BONUS)":  "RF",
    "XGBoost (BONUS)":        "XGB",
}
CLF_MAP = {
    "Logistic Regression":     "LR",
    "K-Nearest Neighbors":     "KNN",
    "SVM (BONUS)":             "SVM",
    "Neural Network (BONUS)":  "MLP",
}

lines = ["% Auto-generated by inject_metrics.py — do not edit by hand.", ""]

# Dataset macros
lines += [
    fr"\newcommand{{\DSROWS}}{{{n_rows:,}}}",
    fr"\newcommand{{\DSFEATURES}}{{{n_features}}}",
    fr"\newcommand{{\DCSHORTPCT}}{{{short_pct}}}",
    fr"\newcommand{{\DCMEDPCT}}{{{medium_pct}}}",
    fr"\newcommand{{\DCLONGPCT}}{{{long_pct}}}",
    "",
]

# Per-regression-model macros: \REGLRRTWO, \REGLRRMSE, \REGLRMAE, etc.
for full, stem in REG_MAP.items():
    r = reg[full]
    lines += [
        fr"\newcommand{{\REG{stem}RTWO}}{{{fmt4(r['R2'])}}}",
        fr"\newcommand{{\REG{stem}RMSE}}{{{fmt3(r['RMSE'])}}}",
        fr"\newcommand{{\REG{stem}MAE}}{{{fmt3(r['MAE'])}}}",
    ]
lines.append("")

# Best-regression aggregate macros
br = reg[best_reg_key]
lines += [
    fr"\newcommand{{\REGBESTNAME}}{{{best_reg_key.replace(' (BONUS)','*')}}}",
    fr"\newcommand{{\REGBESTRTWO}}{{{fmt4(br['R2'])}}}",
    fr"\newcommand{{\REGBESTRMSE}}{{{fmt3(br['RMSE'])}}}",
    fr"\newcommand{{\REGBESTMAE}}{{{fmt3(br['MAE'])}}}",
    "",
]

# Per-classification-model macros
for full, stem in CLF_MAP.items():
    c = clf[full]
    lines += [
        fr"\newcommand{{\CLF{stem}ACC}}{{{fmt3(c['Accuracy'])}}}",
        fr"\newcommand{{\CLF{stem}PRE}}{{{fmt3(c['Precision'])}}}",
        fr"\newcommand{{\CLF{stem}REC}}{{{fmt3(c['Recall'])}}}",
        fr"\newcommand{{\CLF{stem}FON}}{{{fmt3(c['F1'])}}}",
    ]
lines.append("")

# Best-classification aggregate
bc = clf[best_clf_key]
lines += [
    fr"\newcommand{{\CLFBESTNAME}}{{{best_clf_key.replace(' (BONUS)','*')}}}",
    fr"\newcommand{{\CLFBESTACC}}{{{fmt3(bc['Accuracy'])}}}",
    fr"\newcommand{{\CLFBESTFONE}}{{{fmt3(bc['F1'])}}}",
    "",
]

(HERE / "metrics.tex").write_text("\n".join(lines))
print(f"Wrote {HERE / 'metrics.tex'} — {len(lines)} lines")
print(f"Best regression: {best_reg_key}  R2={br['R2']:.4f}  RMSE={br['RMSE']:.3f}")
print(f"Best classifier: {best_clf_key}  Acc={bc['Accuracy']:.3f}  F1={bc['F1']:.3f}")
