"""
Read saved_models/metrics.json (produced by models.py) and emit metrics.tex
defining every \\REG... and \\CLF... and \\DC... and \\DS... macro used in main.tex.

This guarantees that every numerical claim in the report comes from a real
execution of the pipeline.
"""
import json
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
SAVED = PROJECT / "saved_models"

metrics = json.loads((SAVED / "metrics.json").read_text(encoding="utf-8"))
metadata = json.loads((SAVED / "metadata.json").read_text(encoding="utf-8"))

reg = metrics["regression"]
clf = metrics["classification"]
best_reg_key = metrics["best_regression_model"]
best_clf_key = metrics["best_classification_model"]

# Class distribution and dataset size — derived from the dataset directly
df = pd.read_csv(PROJECT / "LengthOfStay.csv")
los = df["lengthofstay"]
n_short  = int((los <= 3).sum())
n_medium = int(((los > 3) & (los <= 7)).sum())
n_long   = int((los > 7).sum())
total    = n_short + n_medium + n_long
short_pct  = f"{n_short  / total * 100:.1f}\\%"
medium_pct = f"{n_medium / total * 100:.1f}\\%"
long_pct   = f"{n_long   / total * 100:.1f}\\%"
n_rows     = len(df)
# Approximate feature count after preprocessing one-hot expansion
n_features = len(metadata["feature_columns"])


def fmt3(v): return f"{v:.3f}"
def fmt4(v): return f"{v:.4f}"

REG_MAP = {
    "Linear Regression":      "LR",
    "Decision Tree":          "DT",
    "Random Forest (BONUS)":  "RF",
    "XGBoost (BONUS)":        "XGB",
}
CLF_MAP = {
    "Logistic Regression":              "LR",
    "KNN":                              "KNN",
    "Linear SVM (BONUS)":               "SVM",
    "Random Forest Classifier (BONUS)": "RFC",
    "Neural Network (BONUS)":           "MLP",
}

lines = ["% Auto-generated by inject_metrics.py — do not edit by hand.", ""]

lines += [
    fr"\newcommand{{\DSROWS}}{{{n_rows:,}}}",
    fr"\newcommand{{\DSFEATURES}}{{{n_features}}}",
    fr"\newcommand{{\DCSHORTPCT}}{{{short_pct}}}",
    fr"\newcommand{{\DCMEDPCT}}{{{medium_pct}}}",
    fr"\newcommand{{\DCLONGPCT}}{{{long_pct}}}",
    "",
]

for full, stem in REG_MAP.items():
    if full not in reg:
        raise SystemExit(f"Missing regression model in metrics.json: {full}")
    r = reg[full]
    lines += [
        fr"\newcommand{{\REG{stem}RTWO}}{{{fmt4(r['R2'])}}}",
        fr"\newcommand{{\REG{stem}RMSE}}{{{fmt3(r['RMSE'])}}}",
        fr"\newcommand{{\REG{stem}MAE}}{{{fmt3(r['MAE'])}}}",
    ]
lines.append("")

br = reg[best_reg_key]
lines += [
    fr"\newcommand{{\REGBESTNAME}}{{{best_reg_key.replace(' (BONUS)','*')}}}",
    fr"\newcommand{{\REGBESTRTWO}}{{{fmt4(br['R2'])}}}",
    fr"\newcommand{{\REGBESTRMSE}}{{{fmt3(br['RMSE'])}}}",
    fr"\newcommand{{\REGBESTMAE}}{{{fmt3(br['MAE'])}}}",
    "",
]

for full, stem in CLF_MAP.items():
    if full not in clf:
        raise SystemExit(f"Missing classification model in metrics.json: {full}")
    c = clf[full]
    lines += [
        fr"\newcommand{{\CLF{stem}ACC}}{{{fmt3(c['Accuracy'])}}}",
        fr"\newcommand{{\CLF{stem}PRE}}{{{fmt3(c['Precision'])}}}",
        fr"\newcommand{{\CLF{stem}REC}}{{{fmt3(c['Recall'])}}}",
        fr"\newcommand{{\CLF{stem}FON}}{{{fmt3(c['F1'])}}}",
        fr"\newcommand{{\CLF{stem}LREC}}{{{fmt3(c['LongStayRecall'])}}}",
    ]
lines.append("")

bc = clf[best_clf_key]
lines += [
    fr"\newcommand{{\CLFBESTNAME}}{{{best_clf_key.replace(' (BONUS)','*')}}}",
    fr"\newcommand{{\CLFBESTACC}}{{{fmt3(bc['Accuracy'])}}}",
    fr"\newcommand{{\CLFBESTFONE}}{{{fmt3(bc['F1'])}}}",
    fr"\newcommand{{\CLFBESTLREC}}{{{fmt3(bc['LongStayRecall'])}}}",
    "",
]

(HERE / "metrics.tex").write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {HERE / 'metrics.tex'} — {len(lines)} lines")
print(f"Best regression: {best_reg_key}  R2={br['R2']:.4f}  RMSE={br['RMSE']:.3f}")
print(f"Best classifier: {best_clf_key}  Acc={bc['Accuracy']:.3f}  F1={bc['F1']:.3f}  LongRec={bc['LongStayRecall']:.3f}")
